image: williamyeh/ansible:debian8

before_script:
    - apt-get update
    - apt-get -y install patch

variables:
    HOSTNAME: default.example.org

job1:
    script: "ansible-playbook ispmail.yml -l localhost"

