---

- hosts: all
  roles:
  - ispmail-packages
  - dumpvars
  - thydel.patch
  - ispmail-certificate
  - ispmail-database
  - ispmail-postfix
  - ispmail-dovecot
  - ispmail-webmail
  - ispmail-webmail-apache

