---
- name: Installing required Python mysqldb module for Ansible to manage databases
  apt:
    name:
      - python3-pymysql

- name: creating mailserver MySQL database
  mysql_db:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    name: mailserver
- name: copying MySQL database schema to server
  copy:
    src: schema.sql
    dest: /tmp
- name: setting up SQL schema of mailserver database
  mysql_db:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    name: mailserver
    state: import
    target: /tmp/schema.sql
- name: creating MySQL user mailadmin
  mysql_user:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    name: mailadmin
    password: "{{ispmail_mysql_mailadmin_password}}"
    priv: mailserver.*:SELECT,INSERT,UPDATE,DELETE
    host: localhost
- name: creating MySQL user to read the mailserver database
  mysql_user:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    name: mailserver
    password: "{{ispmail_mysql_mailserver_password}}"
    priv: mailserver.*:SELECT
    host: 127.0.0.1
- name: copying MySQL test data to server
  copy:
    src: test.sql
    dest: /tmp
  when: ispmail_populate_test_data == true
- name: populating the database with test data
  mysql_db:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    name: mailserver
    state: import
    target: /tmp/test.sql
  when: ispmail_populate_test_data == true
