---
- name: install required binary packages
  apt:
    name: "{{ packages }}"
    update_cache: yes
  vars:
    packages:
    - mariadb-server
    - postfix
    - postfix-mysql
    - roundcube
    - roundcube-mysql
    - roundcube-plugins
    - roundcube-plugins-extra
    - swaks
    - dovecot-mysql
    - dovecot-pop3d
    - dovecot-imapd
    - dovecot-lmtpd
    - dovecot-managesieved
    - adminer
    - rspamd
# TODO: shorewall

# - name: purge Exim installation
#   apt: name={{item}} state=absent purge=yes
#   with_items:
#   - exim4
#   - exim4-base
#   - exim4-config
#   - exim4-daemon-light

# - name: make sure mysql-server is started
#   service: name=mysql enabled=yes state=started
