---
- name: install required binary packages
  apt:
    name: "{{ packages }}"
    update_cache: yes
  vars:
    packages:
      - etckeeper
      - certbot
      - pwgen
      - mariadb-server
      - postfix
      - postfix-mysql
      # - roundcube
      # - roundcube-mysql
      # - roundcube-plugins
      # - roundcube-plugins-extra
      - swaks
      - dovecot-mysql
      - dovecot-pop3d
      - dovecot-imapd
      - dovecot-lmtpd
      - dovecot-managesieved
      - apache2
      - php
      - adminer
      - rspamd
      - fail2ban
      - ca-certificates
      - mutt
# TODO: shorewall
