---
# Check that this system is Debian Bullseye.
# Other Debian derivates may work but are untested.
- hosts: all
  tags: always
  tasks:
    - name: "Checking operating system version"
      assert:
        that: ansible_distribution_release == 'bullseye'
        fail_msg: "This Ansible playbook is only supported on Debian Bullseye."
        success_msg: "Debian Bullseye found. That makes me happy."

- hosts: all
  tags: always
  tasks:
    - include_tasks: detect_fqdn.yml
      when: ispmail_fqdn is not defined

- hosts: all
  roles:
    #- dumpvars
    - role: ispmail-packages
      tags: packages
    - role: geerlingguy.certbot
      tags: certbot
    - role: ispmail-database
      tags: database
    - role: ispmail-postfix
      tags: postfix
    - role: ispmail-dovecot
      tags: dovecot
    - role: ispmail-webmail-apache-roundcube
      tags: roundcube
    - role: ispmail-rspamd
      tags: rspamd

- hosts: all
  tags: always
  tasks:
    - debug:
        msg:
          - "Installation complete."
          - ""
          - "Web mail URL:            https://{{ispmail_fqdn}}/"
          - "Example email user:      john@{{ispmail_fqdn}}"
          - "Example email password:  summersun"
          - "Rspamd admin URL:        https://{{ispmail_fqdn}}/rspamd"
          - "Rspamd admin password:   {{ispmail_rspamd_web_password}}"
